name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js version 23
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
      - run: npm install
      - run: npm run build --prefix client
